name: Prepare Upstream QMK Firmware with Balu's Patches

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 4 * * *'

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: qmk/qmk_firmware
      UPSTREAM_BRANCH: master
      FORK_BRANCH: master
      PATCH_URL: https://github.com/qmk/qmk_firmware/compare/master...balub:qmk_firmware:master.patch

    steps:
      - name: Set up Git user # most of this step doesn't matter. previous repo was operating on itself, this one clones every time. This is just to make git work
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          #git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          #git fetch upstream
          git clone https://github.com/${{ env.UPSTREAM_REPO }}.git --recurse-submodules qmk_src

      - name: Reset fork branch to upstream/master
        run: |
          cd qmk_src
          git reset --hard upstream/${{ env.UPSTREAM_BRANCH }}

      - name: Download and apply balub's patches (merge, prefer our changes)
        run: |
          cd qmk_src
          curl -L "${PATCH_URL}" -o ~/balub.patch
          git am -3 --keep-non-patch ~/balub.patch || \
          (git am --abort && git apply --3way --reject ~/balub.patch)

      #- name: Push to fork
      #  run: |
      #    git push origin ${{ env.FORK_BRANCH }} --force
      - name: Build
        run: |
          echo "this is just a placeholder. For now we will show the git log difference from upstream"
          git log origin/${{ env.UPSTREAM_BRANCH }}..HEAD
