name: Prepare Upstream QMK Firmware with Balu's Patches

on:
  workflow_dispatch:
  push: 
    branches: ["main"]
  #schedule:
  #  - cron: '0 4 * * *'

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: qmk/qmk_firmware
      UPSTREAM_BRANCH: master
      FORK_BRANCH: master
      PATCH_URL: https://github.com/qmk/qmk_firmware/compare/master...balub:qmk_firmware:master.patch

    steps:
      - name: Add upstream remote and fetch
        run: |
          #git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          #git fetch upstream
          git clone https://github.com/${{ env.UPSTREAM_REPO }}.git --recurse-submodules qmk_src
          cd qmk_src
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git # QMK NEEDS THIS!
          git remote -v

      - name: Set up Git user # most of this step doesn't matter. previous repo was operating on itself, this one clones every time. This is just to make git work
        run: |
          cd qmk_src
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

#      - name: Reset fork branch to upstream/master # this is also not needed, leftover from previous repo
#        run: |
#          cd qmk_src
#          #git reset --hard upstream/${{ env.UPSTREAM_BRANCH }}
#          git reset --hard origin/${{ env.UPSTREAM_BRANCH }}

      - name: Download and apply balub's patches (merge, prefer our changes)
        run: |
          cd qmk_src
          curl -L "${PATCH_URL}" -o ~/balub.patch
          git am -3 --keep-non-patch ~/balub.patch || \
          (git am --abort && git apply --3way --reject ~/balub.patch)

      #- name: Push to fork
      #  run: |
      #    git push origin ${{ env.FORK_BRANCH }} --force
      - name: Verify
        run: |
          echo "This will show the git log difference from upstream"
          cd qmk_src
          git log origin/${{ env.UPSTREAM_BRANCH }}..HEAD
      - name: Build
        run: |
          echo "Fetching deps"
          sudo apt update

          sudo apt install -y git python3-pip 

          sudo apt install -y gcc-arm-none-eabi  || true
          sudo apt install -y gcc-avr avr-libc avrdude  || true
          sudo apt install -y dfu-programmer dfu-util || true


          pip install --user qmk || true # Allow failing
          pip install --user qmk --break-system-packages || true # Allow failing 
          
          cd qmk_src
          git submodule update --init --recursive
          
          echo "Running QMK Setup"
          yes | $HOME/.local/bin/qmk setup
          qmk compile -kb handwired/corydora -km default
